name: Check for API Breaking Changes

on: [pull_request]

concurrency: # cancel previous workflow run if one exists
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  check-api-breaking-changes:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      
      - uses: customerio/mobile-ci-tools/github-actions/ios/setup-ios/v1@MacOS-15+iOS-26
      
      - name: Install sourcekitten
        run: brew install sourcekitten
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          ruby-version: '3.2'
          bundler-cache: false # we don't need bundler for this workflow

      - name: Check for API changes
        run: |
          # Run the API change detection script
          ruby scripts/check-api-changes.rb
